name: Workflow PR Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write 

    env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        NUGET_XMLDOC_MODE: skip
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: build
          uses: ./.github/actions/task-group-build
        
        - name: test
          uses: ./.github/actions/task-group-test-coverage
        
        - name: publish result
          uses: ./.github/actions/task-group-publish-coverage-comments