name: Workflow Branch Build

on:
 push:
    branches:
      - main

concurrency:
  group: "CoverageReport"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        NUGET_XMLDOC_MODE: skip
    permissions:
      contents: write
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: build
          uses: ./.github/actions/task-group-build
        
        - name: test
          uses: ./.github/actions/task-group-test-coverage
        
        - name: publish result
          uses: ./.github/actions/task-group-publish-coverage-report
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
